project:
  project: retinotopic mapping
  application: sequence stimuli
  version: 1.0

display:
  screenId: 0 # screen id: 0, 1, ...
  width: 1920 # pixels
  height: 1080 # pixels
  # width: 1366
  # height: 768

imgSize:
  width: 600 # pixels
  height: 600 # pixels

extensions:
  - .jpg
  - .png

prompt:
  img: img/prompt.jpg

temporalDesign:
  startOffset: 10 # seconds

control:
  quitKeyName: Key_Escape
  startKeyName: Key_S

imgSequence:
  paddingBefore: 0 # seconds
  paddingAfter: 1 # seconds
  duration: 3 # seconds
  background: [0, 0, 0, 255]

focusPoint:
  toggled: true
  radius: 5 # pixels
  alpha: 200 # alpha
  tMin: 5
  tMax: 10
  colors:
    - "#E22"
    - "#2E2"
    - "#22E"
    - "#E2E"
    - "#EE2"
    - "#EEE"

colors:
  debugColor: "#D0104C"
