project:
  project: retinotopic mapping
  application: screen stimuli
  version: 1.0

display:
  screenId: 0 # screen id: 0, 1, ...
  width: 1920 # pixels
  height: 1080 # pixels
  # width: 800
  # height: 600

prompt:
  img: img/prompt.jpg

control:
  quitKeyName: Key_Escape
  startKeyName: Key_S

temporalDesign:
  startOffset: 10 # seconds

checkboxTexture:
  colored: false # boolean, not used yet
  numInLatitude: 12 # number
  numInLongitude: 20 # number
  flickingRate: 4 # Hz

eccentricityMapping:
  width: 60 # pixels
  duration: 40 # seconds
  minRadius: 20 # pixels
  maxRadius: 400 # pixels
  repeat: 1 # times, not used yet
  background: [0, 0, 0, 255]

polarAngleMapping:
  width: 45 # degrees
  duration: 10 # seconds
  minRadius: 20 # pixels
  maxRadius: 400 # pixels
  repeat: 2 # times, not used yet
  background: [0, 0, 0, 255]

focusPoint:
  toggled: true
  radius: 5 # pixels
  alpha: 200 # alpha
  tMin: 5
  tMax: 10
  colors:
    - "#E22"
    - "#2E2"
    - "#22E"
    - "#E2E"
    - "#EE2"
    - "#EEE"

colors:
  debugColor: "#D0104C"
