project:
  project: retinotopic mapping
  application: screen stimuli
  version: 1.0

display:
  screenId: 0 # screen id: 0, 1, ...
  # width: 1920 # pixels
  # height: 1080 # pixels
  width: 800
  height: 600

prompt:
  img: img/prompt.jpg

control:
  quitKeyName: Key_Escape
  startKeyName: Key_S

checkboxTexture:
  colored: false # boolean
  numInLatitude: 12 # number
  numInLongitude: 20 # number
  flickingRate: 0.5 # Hz

eccentricityMapping:
  width: 60 # pixels
  duration: 10 # seconds
  minRadius: 20 # pixels
  maxRadius: 400 # pixels
  repeat: 2 # times

polarAngleMapping:
  width: 45 # degrees
  duration: 10 # seconds
  minRadius: 20 # pixels
  maxRadius: 400 # pixels
  repeat: 2 # times
